### ISSUE TITLE
Proposal: Per-task generation counter

### ISSUE THREAD

**Issue by thynnmas** [DanEngelbrecht/bikeshed#56]
Hi,

This is not a bug report, but me asking if you'd want a pull request that changed the generation counter to reduce the chance of stale task IDs being misused.

Some of our engine still uses an older system that wraps bikeshed internally, and stores some additional data for each task. We have been using the bikeshed task IDs as identifiers for this data to do cleanup, which means there would be a short time after a task completed where the (now stale) task ID would still be assumed to be unique. This (unsafe) assumption would be violated in automated soak tests, after about 3 days of uptime on average. This is obviously a bug on our end, but it got me looking into the generation bits of the task ID.

The current generation counter strataegy for task IDs (`m_TaskGeneration`) of a shared generation that gets incremented in each `CreateTask` call means wrap-around can happen relatively quickly, and it is in theory possible for a task ID to be reused with the same exact generation counter on subsequent uses of the same task slot/index. 
We've made a local change where we instead increment the generation directly in the task ID field in the task data. This means we need to initialize this on on startup, but it means the generation bit no longer wraps around every 512 tasks (worst-case, with 1 task per `CreateTasks` call), but every 512 usages of each task slot, drastically reducing the chance of a stale ID matching a live one.

Whether this improves or worsens performance depends on usage characteristics; because the task slots are reserved by the time we increment the generation, we no longer need the this to be atomic, but it does mean that every task added needs to do some minor work & adds a load->store dependency in that loop. If this is a win or loss will depend on contention and on amount of tasks per call. 
The extra cost on initialization is always there, although if that performance is super important, those bits could be left uninitialized without anything breaking.

I've attached a [patch](https://github.com/DanEngelbrecht/bikeshed/files/14615241/generations.patch) with the changes we've made, applied to the current repository, and checked that all tests still pass.

If you want the changes, but as a pull request, let me know.

**Comment by DanEngelbrecht** [comment]
Thanks, will have a look. Not sure when.

**Comment by DanEngelbrecht** [comment]
I made a variant of your changes, please have a look at https://github.com/DanEngelbrecht/bikeshed/pull/57
Biggest difference is that I chose not to zero out the task ids as we don't really care what number the generation is, just that we add 1 to each time a task id is used. Masking takes care of keeping the generation and task id separate.

**Comment by thynnmas** [comment]
That looks good to me 👍. Thanks for having a look.
